# Generated by Django 3.2.18 on 2023-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continents',
            name='describe',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
