list_of_countries  = ['afghanistan',
 'albania',
 'algeria',
 'american samoa',
 'angola',
 'anguilla',
 'antigua and barbuda',
 'argentina',
 'armenia',
 'aruba',
 'australia',
 'austria',
 'azerbaijan',
 'bahrain',
 'bangladesh',
 'barbados',
 'belarus',
 'belgium',
 'belize',
 'benin',
 'bermuda',
 'bhutan',
 'bolivia',
 'bosnia and herzegovina',
 'botswana',
 'brazil',
 'british indian ocean territory',
 'brunei',
 'bulgaria',
 'burkina faso',
 'burundi',
 'cambodia',
 'cameroon',
 'canada',
 'cape verde',
 'cayman islands',
 'central african republic',
 'chad',
 'chile',
 'china',
 'christmas island',
 'cocos (keeling) islands',
 'colombia',
 'comoros',
 'cook islands',
 'costa rica',
 'croatia',
 'cuba',
 'cyprus',
 'czech republic',
 'democratic republic of the congo',
 'denmark',
 'djibouti',
 'dominica',
 'dominican republic',
 'east timor',
 'ecuador',
 'egypt',
 'el salvador',
 'equatorial guinea',
 'eritrea',
 'estonia',
 'ethiopia',
 'falkland islands',
 'faroe islands',
 'federated states of micronesia',
 'fiji',
 'finland',
 'france',
 'french guiana',
 'french polynesia',
 'french southern and antarctic lands',
 'gabon',
 'georgia',
 'germany',
 'ghana',
 'gibraltar',
 'greece',
 'greenland',
 'grenada',
 'guadeloupe',
 'guam',
 'guatemala',
 'guernsey',
 'guinea',
 'guinea-bissau',
 'guyana',
 'haiti',
 'heard island and mcdonald islands',
 'honduras',
 'hong kong',
 'hungary',
 'iceland',
 'india',
 'indonesia',
 'iran',
 'iraq',
 'ireland',
 'isle of man',
 'israel',
 'italy',
 'ivory coast',
 'jamaica',
 'japan',
 'jersey',
 'jordan',
 'kazakhstan',
 'kenya',
 'kiribati',
 'kuwait',
 'kyrgyzstan',
 'laos',
 'latvia',
 'lebanon',
 'lesotho',
 'liberia',
 'libya',
 'liechtenstein',
 'lithuania',
 'luxembourg',
 'macau',
 'madagascar',
 'malawi',
 'malaysia',
 'maldives',
 'mali',
 'malta',
 'marshall islands',
 'martinique',
 'mauritania',
 'mauritius',
 'mayotte',
 'mexico',
 'moldova',
 'monaco',
 'mongolia',
 'montserrat',
 'morocco',
 'mozambique',
 'namibia',
 'nauru',
 'nepal',
 'netherlands',
 'new caledonia',
 'new zealand',
 'nicaragua',
 'niger',
 'nigeria',
 'niue',
 'norfolk island',
 'north korea',
 'northern mariana islands',
 'norway',
 'oman',
 'pakistan',
 'palau',
 'panama',
 'papua new guinea',
 'paraguay',
 'peru',
 'philippines',
 'pitcairn islands',
 'poland',
 'portugal',
 'puerto rico',
 'qatar',
 'republic of macedonia',
 'republic of the congo',
 'romania',
 'russia',
 'rwanda',
 'réunion',
 'saint helena',
 'saint kitts and nevis',
 'saint lucia',
 'saint pierre and miquelon',
 'saint vincent and the grenadines',
 'samoa',
 'san marino',
 'saudi arabia',
 'scotland',
 'senegal',
 'serbia',
 'seychelles',
 'sierra leone',
 'singapore',
 'slovakia',
 'slovenia',
 'solomon islands',
 'somalia',
 'south africa',
 'south georgia',
 'south korea',
 'south sudan',
 'spain',
 'sri lanka',
 'sudan',
 'suriname',
 'svalbard and jan mayen',
 'swaziland',
 'sweden',
 'switzerland',
 'syria',
 'são tomé and príncipe',
 'taiwan',
 'tajikistan',
 'tanzania',
 'thailand',
 'the bahamas',
 'the gambia',
 'togo',
 'tokelau',
 'tonga',
 'trinidad and tobago',
 'tunisia',
 'turkey',
 'turkmenistan',
 'tuvalu',
 'uganda',
 'ukraine',
 'united arab emirates',
 'united kingdom',
 'united states',
 'uruguay',
 'uzbekistan',
 'vanuatu',
 'venezuela',
 'vietnam',
 'wales',
 'wallis and futuna',
 'western sahara',
 'yemen',
 'zambia',
 'zimbabwe']